version: '3.5'

services:
  skolboard-postgres:
    image: postgres:latest
    container_name: skolboard-postgres
    user: ${POSTGRES_USER}
    networks:
      - skolboard-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_DOCKER_PORT}:5432

    volumes:
      - ./postgres.conf:/etc/postgresql.conf:ro
      - skolboard-postgres-dbdata:/var/lib/postgresql/data:rw

  skolboard-api:
    build:
      dockerfile: deployment/Dockerfile
      context: ..
    image: skolboard-api
    container_name: skolboard-api
    networks:
      - skolboard-network
    ports:
      - ${API_HOST}:${API_PORT}:${API_PORT}
    depends_on:
      - skolboard-postgres

    volumes:
      - ../:/code:rw
    command: >
      sh -c "python manage.py runserver 0.0.0.0:${API_PORT}"
    restart: always

volumes:
  skolboard-postgres-dbdata:
    name: skolboard-postgres-dbdata


networks:
  skolboard-network: