version: '3.5'

services:
  skolboard-postgres:
    image: postgres:latest
    container_name: skolboard-postgres
    user: ${POSTGRES_USER}
    networks:
      - skolboard-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_OUTER_PORT}:5432
    logging:
      driver: "journald"
      options:
        tag: skolboard-api
    volumes:
      - skolboard-postgres-dbdata:/var/lib/postgresql/data:rw

  skolboard-api:
    build:
      dockerfile: Dockerfile
      context: ..
    image: skolboard-api
    container_name: skolboard-api
    networks:
      - skolboard-network
    ports:
      - ${API_EXTERNAL_HOST}:${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}
    depends_on:
      - skolboard-postgres
    logging:
      driver: "journald"
      options:
        tag: skolboard-api
    volumes:
      - ../:/code:rw
    command: >
      sh -c "python manage.py migrate &
             python manage.py runserver ${}"
    restart: always

volumes:
  skolboard-postgres-dbdata:
    name: skolboard-postgres-dbdata

networks:
  skolboard-network: