# Generated by Django 3.0.2 on 2020-01-22 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200122_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
