# Generated by Django 3.0.2 on 2020-01-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200122_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(db_table='skolboard_post_tags', related_name='posts', to='board.Tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(0, 'PERSON'), (1, 'ORGANIZATION')], default=0),
        ),
        migrations.DeleteModel(
            name='PostTagRelation',
        ),
    ]
