# Generated by Django 3.0.2 on 2020-01-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_profile_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
