# Generated by Django 2.2 on 2020-01-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20200122_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_dttm']},
        ),
    ]
